import json

path = r"c:\Users\Таня\Desktop\Folder\Projects\langosoft\frontend\public\mnemonics.json"

with open(path, encoding="utf-8") as f:
    existing = json.load(f)

new_entries = {
  "a": "A finger pointing AT / TO the target.",
  "abbandonai": "(abbandonare) An ABANDONED BUNNY alone — I LEFT / ABANDONED the group.",
  "accio": "ACHOO! sneezing SO THAT everyone turns around.",
  "acquista": "(acquistare) ACQUISITION form stamped: BUYS / ACQUIRES new land.",
  "affannata": "(affannare) A FAN sprinting upstairs, PANTING / OUT OF BREATH.",
  "ahi": "AHI! A sharp cry — ALAS, that hurt!",
  "aiutami": "(aiutare) MY EYE! I NEED HELP — HELP ME!",
  "al": "AL Pacino marching TO THE stage.",
  "allor": "(allora) AL GORE checking his watch — THEN / AT THAT TIME he spoke.",
  "alta": "(alto) ALTA ski slope: HIGH and steep.",
  "alto": "An ALTO voice singing HIGH notes in the choir.",
  "altri": "ALTRUISM means caring for OTHERS.",
  "altro": "ALTERnative route: ANOTHER path, something ELSE.",
  "altrui": "ALTRUISM for OTHERS — their generosity, not yours.",
  "amara": "(amaro) AMARETTO liqueur: BITTER almond taste.",
  "ambedui": "AMBiguous DUO: BOTH of them unclear.",
  "amore": "AMORE! An Italian serenade of LOVE.",
  "ancor": "(ancora) An ANCHOR holding the ship STILL / YET.",
  "ancora": "An ANCHOR planted in the seabed — STILL / AGAIN it holds.",
  "anima": "ANIMA — the SOUL, literally the inner spirit.",
  "animali": "ANIMALS roaming wild — quite literally ANIMALS.",
  "antichi": "(antico) ANTIQUE shop full of ANCIENT / OLD things.",
  "anzi": "ANXIETY? ON THE CONTRARY, I am perfectly calm.",
  "aspra": "(aspro) ASPIRIN too HARSH / BITTER to swallow dry.",
  "augusto": "AUGUST CAESAR: MAJESTIC / NOBLE emperor of Rome.",
  "autore": "AUTHOR: the CREATOR of the story.",
  "basso": "BASS guitar thumping at the LOW / DEEP end.",
  "beate": "(beato) BEATITUDE: BLESSED / HAPPY state of grace.",
  "belle": "(bello) BELLE: A BEAUTIFUL princess in a fairy tale.",
  "bello": "BELLBOY welcoming you — BEAUTIFUL service.",
  "ben": "(bene) Big BEN striking the hour: all is WELL / TRULY.",
  "bene": "BENEFACTOR — everything is WELL / GOOD.",
  "bestia": "A BEAST stomping through the forest.",
  "brame": "(brama) BRAMBLES full of LONGINGS / CRAVINGS to reach the fruit.",
  "bramosa": "(bramare) A BRAHMA bull CRAVING / YEARNING the prize.",
  "bugiardi": "(bugiardo) A BOO-ING GUARD who catches LIARS red-handed.",
  "buono": "BUENOS dias — GOOD morning! GOOD and fine.",
  "caccera": "(cacciare) CATCH-A rat: WILL CHASE / HUNT it down.",
  "cagion": "(cagione) A CAGE with the REASON / CAUSE locked inside.",
  "cagione": "A CAGE-IONE: the CAUSE / REASON is trapped inside.",
  "calle": "CALLEY-way: a narrow LANE / PATH between walls.",
  "cammilla": "CAMILLA riding a horse — a warrior maiden.",
  "cammino": "A CAMEL going on a long JOURNEY / PATH.",
  "campar": "(campare) CAMP survival art: TO LIVE / SURVIVE in the wild.",
  "cantai": "(cantare) CHANT — I SANG like a monk.",
  "carca": "CARGO ship LADEN / LOADED with weight.",
  "cercar": "(cercare) SEARCH-CAR cruising, SEEKING / SEARCHING.",
  "certo": "CERTIFY: make CERTAIN / SURE beyond doubt.",
  "che": "A KEY that opens THAT door BECAUSE it fits.",
  "chi": "A KEY for WHOEVER holds it — WHO may enter?",
  "ciascun": "(ciascuno) EACH SCENE: EACH ONE performs separately.",
  "cibera": "(cibarsi) A CUB EATING / FEEDING on wild berries.",
  "citta": "CITY — same word, same meaning.",
  "cio": "A CELLO playing THAT specific note — THIS / THAT.",
  "colle": "COLLAR sitting on a dog atop a HILL.",
  "color": "(coloro) COLORFUL crowd — THOSE PEOPLE in all their hues.",
  "colui": "COOL ONE — HE is THE ONE, that guy.",
  "combusto": "(comburere) COMBUSTION: BURNED / CONSUMED entirely.",
  "come": "COME as you are — HOW / AS you naturally are.",
  "cominciar": "(cominciare) A COMMISSIONER blows his whistle TO BEGIN the race.",
  "compunto": "(compungere) COMPUNCTION: a sharp STAB of REMORSE / REGRET.",
  "con": "CONVOY moving WITH its escort.",
  "conoscesti": "(conoscere) CONNOISSEUR: YOU KNEW / RECOGNIZED the finest wines.",
  "contenti": "(contento) CONTENT: SATISFIED / HAPPY with the outcome.",
  "contra": "CONTRARY opinion: AGAINST the mainstream.",
  "convien": "(convenire) CONVENIENT: IT IS NECESSARY to make it work.",
  "cor": "(cuore) CORE — the HEART of the matter.",
  "corpo": "CORPSE or CORPORATION: a BODY of people.",
  "cosa": "CAUSE: a THING worth fighting for.",
  "cose": "COZY pile of THINGS scattered around.",
  "costui": "COST YOU: THIS PERSON will cost you.",
  "cosi": "COZY way: THIS is how we do it — SO / THUS.",
  "cotanto": "QUOTA AMOUNT: SO MUCH / SO GREAT beyond measure.",
  "coverta": "(coprire) COVERT operation: COVERED / HIDDEN from view.",
  "cu": "(cui) QUEUE — standing in line, for WHOM exactly?",
  "cui": "QUEUE: standing in line for WHOM / WHICH?",
  "da": "DAD arriving FROM far away.",
  "dal": "A DOLLAR bill coming FROM THE bank.",
  "de": "DEBRIS OF THE collapsed building.",
  "degna": "(degno) DIGNITY: WORTHY of respect.",
  "desse": "(dare) DESSERT she GAVE to the guests.",
  "dicesti": "(dire) DICTATE: YOU SAID / TOLD everyone the terms.",
  "dietro": "DETOUR going BEHIND / BACK the main road.",
  "dilettoso": "(diletto) DELIGHTFUL: PLEASANT and enjoyable.",
  "dinanzi": "NANCY standing right IN FRONT OF / BEFORE you.",
  "dio": "DIOS — GOD in Spanish: same idea.",
  "dipartilla": "(dipartire) DEPART — it LEFT / WENT AWAY from sight.",
  "dir": "(dire) TO SAY / SPEAK directly.",
  "diro": "(dire) I will DECLARE it boldly — I WILL SAY.",
  "discerno": "(discernere) DISCERN: I DISTINGUISH right from wrong.",
  "diserta": "(diserto) DESERT: ABANDONED / DESERTED and dry.",
  "diserto": "DESERT: DESERTED wasteland left behind.",
  "disperate": "(disperato) DESPERATE: DESPAIRING people clutching at hope.",
  "divino": "DIVINE: GODLY perfection beyond the human.",
  "doglia": "DOLL broken in two — PAIN / GRIEF over the loss.",
  "dolce": "DOLCE and Gabbana — SWEET / GENTLE luxury.",
  "dolenti": "(dolente) DOLEFUL: SORROWFUL / SUFFERING faces.",
  "dopo": "DEPOSIT made AFTER the transaction.",
  "dov": "(dove) DOVE bird flying WHERE it pleases.",
  "dove": "A DOVE flying to WHERE it pleases.",
  "dritto": "A DRILL bit going STRAIGHT through the wood.",
  "dura": "(duro) DURABLE material: HARD / LASTING quality.",
  "durata": "DURATION: how LONG something LASTS.",
  "dei": "(dei) DEITY — plural: the GODS of Olympus.",
  "e": "E-mail connecting AND linking two people.",
  "ecco": "ECHO! HERE IT IS — bouncing back at you.",
  "ed": "EDWARD and his brother: AND the rest.",
  "elegge": "(eleggere) ELECTS: voting CHOOSES / SELECTS the winner.",
  "empie": "(empio) EMPIRE built on WICKED / IMPIOUS foundations.",
  "esta": "(questo) ESTATE: THIS property is yours, archaic.",
  "etterno": "(eterno) ETERNAL: lasting FOREVER without end.",
  "eurialo": "EURO-ALIUS — Euryalus, a brave Trojan hero.",
  "fa": "(fare) FACTORY — IT MAKES / PRODUCES things.",
  "face": "(faccia) FACE lit by a TORCH in the dark.",
  "fai": "(fare) DIY — YOU DO / MAKE it yourself.",
  "falsi": "(falso) FALSE IDs: COUNTERFEIT / LYING documents.",
  "fame": "FAMINE: intense HUNGER on a massive scale.",
  "famoso": "FAMOUS: everyone RENOWNED knows your name.",
  "fara": "(fare) PHARAOH commanding: WILL DO / MAKE it happen.",
  "fatto": "(fare) FACTORY output: DONE / MADE, a completed FACT.",
  "fece": "(fare) A FACE-lift was MADE / DID happen.",
  "felice": "FELIX the cat: always HAPPY / FORTUNATE.",
  "feltro": "FELT fabric: soft material like grey FELT.",
  "fermo": "FIRM and STOPPED — solid as a rock, STILL.",
  "ferute": "(ferire) FERRET who got WOUNDED in a trap.",
  "fia": "(essere) FIA Formula 1 authority: IT WILL BE regulated.",
  "fiera": "FIERCE animal prowling the FAIR.",
  "figliuol": "(figlio) FILL YOUR CUP, SON — serve the child.",
  "fin": "(fine) FINISH line: the END of the race.",
  "fioco": "FEEBLE flicker: DIM / FAINT light barely visible.",
  "fiume": "FLUME waterpark: a RIVER of fun.",
  "foco": "(fuoco) FOLK dancing around the FIRE at night.",
  "fonte": "FONT design: the SOURCE / FOUNTAIN of style.",
  "forte": "Your FORTE: your STRONG / LOUD suit.",
  "fosse": "(essere) FOSSIL found in a DITCH / PIT.",
  "fronte": "FRONTMAN on stage: at the FRONT / FOREHEAD.",
  "fu": "(essere) FEW words — it WAS brief.",
  "fugga": "(fuggire) FUGITIVE ordered to FLEE / RUN away.",
  "fuggiva": "(fuggire) FUGITIVE WAS FLEEING through back streets.",
  "fui": "(essere) PHOOEY! I WAS wrong — I admit it.",
  "fuor": "(fuori) FUROR raging OUTSIDE the building.",
  "furon": "(essere) FURORE: THEY WERE furious about it.",
  "fe": "(fede) FAITH kept quietly in the heart.",
  "gaetta": "GAZETTE — the city of Gaeta in the news.",
  "genti": "(gente) GENTRY: PEOPLES / NATIONS of high standing.",
  "gioia": "JOY — pure JOY, like a GEM of happiness.",
  "giugne": "(giungere) JUNE: ARRIVES in the summer heat.",
  "giunto": "(giungere) JUNCTION: ARRIVED / REACHED the crossroads.",
  "giusto": "JUSTICE: JUST / RIGHT and perfectly fair.",
  "gia": "YA know — ALREADY done, ONCE before.",
  "grame": "(gramo) GRIM fate: WRETCHED / MISERABLE condition.",
  "gran": "(grande) GRANDE Starbucks: BIG / GREAT coffee.",
  "grande": "GRAND piano: BIG / GREAT music filling the room.",
  "gravezza": "(grave) GRAVITY: the HEAVINESS / BURDEN pressing down.",
  "grida": "(gridare) GRIDIRON: players SHOUTING across the field.",
  "gridai": "(gridare) GRID: I SHOUTED across the crowded grid.",
  "gride": "(gridare) SHRIEKS: the CRIES echoing all around.",
  "guardai": "(guardare) GUARD position: I LOOKED / WATCHED carefully.",
  "guata": "(guardare) GUAVA being STARED AT by a curious monkey.",
  "guida": "GUIDE: naturally, a GUIDE leading the way.",
  "ha": "(avere) HA! It HAS to be done.",
  "i": "THE plural — I and THE group together.",
  "il": "An EEL: THE slippery one in the water.",
  "ilion": "ILION — Troy itself, the ancient city.",
  "impera": "(imperare) EMPEROR who COMMANDS / RULES the empire.",
  "imperador": "(imperatore) EMPEROR: COMMANDER of all lands.",
  "in": "IN a box — simply inside.",
  "infin": "(in fine) INFINITE time: AT LAST it reaches the end.",
  "io": "IO = I. A mirror reflecting just ME / MYSELF.",
  "italia": "ITALY — the boot-shaped land of pasta.",
  "iulio": "JULIUS Caesar: the great Roman.",
  "ivi": "IVY growing right THERE on the wall.",
  "lago": "LAGOON: a calm sheltered LAKE.",
  "lagrimar": "(lacrimare) LACHRIMAL gland: TO WEEP / SHED TEARS.",
  "largo": "LARGO: a wide, BROAD musical passage.",
  "lascero": "(lasciare) LASSO thrown and released — I WILL LET GO / LEAVE.",
  "lascia": "(lasciare) LASH away: LEAVE it, LET GO now.",
  "lascio": "(lasciare) LASSO dropped: it LEFT / LET GO.",
  "lasso": "LASSO: WEARY cowboy who dropped his rope. ALAS!",
  "le": "LE (French article): THE feminine things.",
  "legge": "LEGAL LAW: the LAW being READ in court.",
  "leggera": "(leggero) LIGHT as a feather — SWIFT / LIGHT and easy.",
  "lei": "LEI (Hawaiian garland): SHE wears it with grace.",
  "lena": "LENA full of ENERGY / VIGOR and drive.",
  "leone": "LEON the LION: a proud king of beasts.",
  "li": "LI = THEM standing over there.",
  "lo": "LOW rider: THE smooth one — HIM.",
  "loco": "(luogo) LOCATION sign: the PLACE to be.",
  "lombardi": "LOMBARDY people: LOMBARDS of northern Italy.",
  "lonza": "BRONZE LYNX leaping — a fierce spotted beast.",
  "lui": "LOUIS pointing directly at HIM.",
  "lume": "LUMINOUS glow: LIGHT from a lamp.",
  "lungo": "LONG espresso: ALONG the LONG route.",
  "lupa": "LUPUS wolf disease: the SHE-WOLF prowling the night.",
  "la": "LA (Los Angeles neon sign): THE city of angels.",
  "ma": "MAD runner yelling: finished BUT still tired!",
  "macolato": "(maculare) MACULATE coat: SPOTTED / STAINED with marks.",
  "maestro": "MAESTRO: the MASTER conductor raising his baton.",
  "magrezza": "(magro) MEAGER rations: extreme THINNESS / LEANNESS.",
  "mai": "NEVER again — MAI = NEVER, not once.",
  "male": "MALEVOLENT: EVIL / BAD intention.",
  "malvagia": "(malvagio) MALEVOLENT: WICKED / EVIL and vile.",
  "mantoani": "(mantoano) MANTUAN: people of Mantua, Virgil's city.",
  "mattino": "MATINS: MORNING prayer at dawn.",
  "me": "ME! Obviously ME, the emphatic self.",
  "mena": "(menare) MENA LEADS everyone forward.",
  "meni": "(menare) MENU: YOU LEAD the choices tonight.",
  "mentre": "MENTOR watching WHILE you train.",
  "mesti": "(mesto) MISTY sadness: SAD / SORROWFUL expressions.",
  "miei": "(mio) MY EYE: looking at MY belongings.",
  "mio": "MY: the simplest possessive — MY own.",
  "miserere": "MISERY: HAVE MERCY on the suffering.",
  "molte": "(molto) MULTITUDE: MANY things piled, feminine.",
  "molti": "(molto) MULTI: MANY people crowding together.",
  "molto": "MOLTEN lava: SO MUCH / VERY intense heat.",
  "montava": "(montare) MOUNTAIN climber WAS MOUNTING the peak.",
  "monte": "MONT Blanc: a MOUNTAIN of ice and glory.",
  "morir": "(morire) MORTUARY: TO DIE and be brought there.",
  "morte": "MORTAL = DEATH awaiting all.",
  "mori": "(morire) MOROSE: he DIED feeling deeply gloomy.",
  "mosse": "(muovere) MOST MOVED: it MOVED everything into action.",
  "nacqui": "(nascere) KNACK: I WAS BORN with a natural gift.",
  "natura": "NATURE: literally the NATURE of things.",
  "nazion": "(nazione) NATION: a people bound as one.",
  "ne": "KNEE: FROM IT / OF IT, a small part.",
  "niso": "NISUS — a loyal Trojan warrior hero.",
  "noia": "NOISE: ANNOYING / BORING buzz you cannot ignore.",
  "non": "NON-sense: simply NOT making sense.",
  "notte": "NOCTURNE: a piece written for the NIGHT.",
  "ne": "NEITHER this NOR that — NE = NEITHER...NOR.",
  "o": "OR this option — O = OR.",
  "occhi": "(occhio) OCULIST examining your EYES.",
  "od": "ODD choice: OR this weird option.",
  "offerto": "(offrire) OFFERED up as a generous gift.",
  "ogne": "(ogni) EVERY single one — EACH and EVERY.",
  "oh": "OH! Simple exclamation of surprise.",
  "ombra": "UMBRELLA casting a SHADOW / SHADE.",
  "omo": "(uomo) HOMO SAPIENS: a MAN of reason.",
  "ond": "(onde) WONDER where it came FROM / WHENCE.",
  "onde": "WONDER where it came FROM / WHENCE.",
  "onore": "HONORABLE: full of HONOR and glory.",
  "or": "(ora) OR NOW — do it NOW, right away.",
  "ove": "(dove) OVEN is WHERE things are baked.",
  "pace": "PACIFIC Ocean: vast PEACE stretching wide.",
  "parea": "(parere) PARABLE: a story that SEEMED meaningful.",
  "parenti": "PARENTS and RELATIVES gathered together.",
  "parlar": "(parlare) PARLIAMENT: SPEAKS for the whole nation.",
  "parti": "(parte) PARTITION: divides into PARTS / LEAVES.",
  "partia": "(partire) PARTING scene: WAS LEAVING / DEPARTING.",
  "partire": "DEPARTURE gate: TO LEAVE, TO PART from here.",
  "passai": "(passare) I PASSED the checkpoint without stopping.",
  "passar": "(passare) PASSOVER: TO PASS / CROSS to the other side.",
  "passo": "PASSPORT checked at every STEP / PACE.",
  "pasto": "PASTA on the table: a hearty MEAL.",
  "patria": "(patria) PATRIOT defending his HOMELAND / FATHERLAND.",
  "paura": "PARANOIA born of FEAR — POWER of pure FEAR.",
  "peggio": "PEG broken — making everything WORSE.",
  "pel": "(per + il) PELLET fired FOR THE target.",
  "pelago": "PELAGIC deep: the vast open SEA.",
  "pelle": "PEEL: SKIN being carefully peeled off.",
  "peltro": "PEWTER mug heavy in the hand.",
  "pensier": "(pensiero) PENSIVE: lost in deep THOUGHT.",
  "penso": "(pensare) PONDER: I THINK it over carefully.",
  "perch": "(perché) PERCH bird always asking BECAUSE / WHY.",
  "perche": "BECAUSE! WHY? BECAUSE logic demands it.",
  "perdei": "(perdere) PERDITION: I LOST everything to ruin.",
  "perder": "(perdere) TO PERISH / LOSE it all completely.",
  "perigliosa": "(periglioso) PERILOUS: DANGEROUS / RISKY at every turn.",
  "persona": "PERSON: simply a human PERSON.",
  "piaggia": "PLAZA on the BEACH / SHORE by the sea.",
  "pianeta": "PLANET: orbiting a PLANET in space.",
  "piange": "(piangere) PLANGENT cry: WEEPING / CRYING out loud.",
  "pien": "(pieno) PLENTY: FULL to the brim with abundance.",
  "pieta": "PITY: COMPASSION for the suffering soul.",
  "pietro": "PETER the apostle — PETER / STONE foundation.",
  "pie": "(piede) PIE at your FOOT — put your FOOT down.",
  "piu": "PLUS: MORE added on top.",
  "poco": "POCKET change: just a LITTLE / FEW coins.",
  "poeta": "POET: literally a POET of words.",
  "poeti": "POETRY: the POETS gathered in a circle.",
  "poi": "POISON ivy stings THEN / AFTERWARDS.",
  "polsi": "(polso) PULSE felt at the WRIST — racing heartbeat.",
  "porse": "(porgere) POUR SOME: OFFERED / EXTENDED a generous gift.",
  "porta": "PORTAL: a DOOR / GATE to another world.",
  "posato": "(posare) POSED / SETTLED calmly in position.",
  "presta": "(prestare) PRESTO! QUICK as a magician trick.",
  "pria": "(prima) PRIMAL instinct: BEFORE / FIRST in everything.",
  "prima": "PRIMA donna: the FIRST / BEFORE all others.",
  "principio": "PRINCIPAL rule: the BEGINNING / PRINCIPLE of it all.",
  "punto": "PUNCTUAL arrival at the exact POINT / MOMENT.",
  "quai": "(quale) QUAIL: WHICH bird is that exactly?",
  "qual": "(quale) QUALITY check: WHICH standard applies?",
  "quando": "A QUANTum physicist checking his watch to see WHEN time stops.",
  "quanto": "QUANTIFY: HOW MUCH is actually there?",
  "quasi": "QUASI-modo: ALMOST / NEARLY normal.",
  "quei": "(quegli) THOSE strange ones — THEY over there.",
  "quel": "(quello)QUEL — THAT particular one.",
  "quella": "(quello) QUELL it: THAT one being silenced.",
  "quelle": "(quello) QUELL: THOSE disturbances, feminine plural.",
  "quello": "QUELLO — YELLOW thing: THAT yellow one.",
  "questa": "(questo) QUEST begins: THIS is the mission.",
  "questi": "(questo) QUESTING knight: THIS one on the quest.",
  "questo": "THIS QUEST right here — QUESTO = THIS one.",
  "queta": "(quieto) QUIET: CALM and perfectly still.",
  "qui": "KEY here: HERE is the key.",
  "quivi": "QUIZ: HERE / IN THIS PLACE is the test.",
  "rabbiosa": "(rabbioso) RABIES: FURIOUS / RABID dog foaming at the mouth.",
  "raggi": "(raggio) RAYS of light: RADIANT beams streaming down.",
  "regge": "(reggere) REGGAE: music that HOLDS / GOVERNS the rhythm.",
  "regna": "(regnare) REIGN: RULES the kingdom with iron hand.",
  "retro": "RETRO style: going BACK in time — BEHIND.",
  "ria": "(rio) RIA inlet hiding WICKED / EVIL secrets.",
  "ribellante": "(ribellare) REBEL flag RISING UP / REBELLING against order.",
  "richeggio": "(richiedere) RICHLY BEGGING: I REQUEST / DEMAND it now.",
  "ridir": "(ridire) REITERATE: TO REPEAT / RETELL the story.",
  "rimessa": "(rimettere) REMISSION: sins FORGIVEN / SENT BACK.",
  "rimirar": "(rimirare) RE-MIRROR: TO GAZE AGAIN at the reflection.",
  "rinova": "(rinnovare) RENEW: it RENEWS / REFRESHES itself.",
  "ripigneva": "(respingere) RE-PUSH: WAS PUSHING / DRIVING BACK.",
  "ripresi": "(riprendere) REPRISE: I RESUMED / TOOK BACK control.",
  "rispuos": "(rispondere) RESPOND: ANSWERED the call.",
  "rispuose": "(rispondere) RESPOND: ANSWERED / REPLIED clearly.",
  "rispuosemi": "(rispondermi) RESPONDED TO ME directly and clearly.",
  "ritornar": "(ritornare) RETURN home: TO GO BACK.",
  "ritorni": "(ritornare) RETURN journey: you RETURN.",
  "riva": "RIVER BANK: standing on the SHORE / BANK.",
  "roma": "ROME: the eternal city of seven hills.",
  "rovinava": "(rovinare) RUIN: WAS RUINING / CRUMBLING to pieces.",
  "saggio": "SAGE: a WISE old sage full of WISDOM.",
  "sali": "(salire) SALUTE going upward — CLIMB! GO UP!",
  "salire": "SAILOR climbing the mast — TO CLIMB / GO UP.",
  "salute": "SALUTE! A toast to HEALTH / SALVATION.",
  "san": "SAINT in short — SAINTLY person.",
  "sanza": "(senza) SANS = WITHOUT (same word in French).",
  "sapienza": "SAPIENT mind: full of WISDOM / KNOWLEDGE.",
  "saranno": "(essere) THEY WILL BE together: SARAH AND NO more waiting.",
  "sara": "(essere) SIR-AH: IT WILL BE Sir final word.",
  "saro": "(essere) A knight dubbed SIR: I WILL BE loyal!",
  "scorte": "(scorta) ESCORTED safely by ESCORTS / GUIDES.",
  "se": "SEBASTIAN wonders IF he should dare.",
  "seconda": "SECONDARY plan: SECOND / ACCORDING TO the rules.",
  "seggio": "SAGE on his SEAT / THRONE of wisdom.",
  "segui": "(seguire) SEQUEL: FOLLOW the next chapter.",
  "selvaggia": "(selvaggio) SAVAGE: WILD / SAVAGE and untamed, feminine.",
  "selvaggio": "SAVAGE beast: WILD and totally untamed.",
  "sembiava": "(sembrare) SEEMED / APPEARED to be something else.",
  "sempre": "SEMPITERNAL: ALWAYS / EVER / STILL enduring.",
  "si": "SIGNAL sent by ONESELF — YES, I confirm.",
  "sia": "(essere) SEA of possibility: wherever it MAY BE.",
  "sii": "(essere) BE! A direct command: just BE yourself.",
  "silenzio": "SILENCE — literally SILENCE all around.",
  "so": "(sapere) SO — I KNOW what you are thinking.",
  "sol": "(sole) SOLO in the SUN: ONLY / ALONE.",
  "solo": "SOLO artist: ALONE / ONLY on stage.",
  "son": "(sono) SON raising his hand: I AM / THEY ARE here!",
  "sonno": "SOMNOLENT: deep SLEEP / SLUMBER taking over.",
  "sotto": "SUBTITLE written UNDER / BENEATH the scene.",
  "spalle": "(spalla) PALLBEARERS carrying weight on SHOULDERS.",
  "spandi": "(spandere) EXPAND: SPREAD it wide and far!",
  "speran": "(sperare) THEY HOPE — speranza rising.",
  "speranza": "ESPERANZA — HOPE in Spanish: the same uplifting word.",
  "sperar": "(sperare) SPARE a moment of HOPE: TO HOPE.",
  "spiriti": "(spirito) SPIRITUAL realm: the SPIRITS and SOULS.",
  "stagione": "STAGNANT SEASON: the SEASON that lingers on.",
  "stelle": "(stella) STELLAR: the STARS shining above.",
  "stilo": "STYLUS pen: a fine STYLE / PEN instrument.",
  "strida": "(stridere) STRIDENT SHRIEKS piercing the night air.",
  "studio": "STUDIO: a room of STUDY / WORK and creation.",
  "sua": "(suo) SUAVE manner: HIS / HER smooth style.",
  "sub": "SUBMARINE: BENEATH / UNDER the surface.",
  "sue": "(suo) SUING someone over HER / HIS belongings.",
  "suoi": "(suo) SOUVENIR: HIS / HER keepsakes from the journey.",
  "superbo": "SUPERB achievement: PROUD / MAGNIFICENT result.",
  "si": "SEE? YES! Confirming with a confident YES.",
  "su": "SUPER going UP — elevated above.",
  "tace": "(tacere) TACO stuffed into the mouth — silence follows.",
  "tal": "(tale) TALL TALE: SUCH a story to tell!",
  "tant": "(tanto) TANTRUM: SUCH GREAT emotion unleashed.",
  "tanta": "(tanto) TANTRUM from SUCH / SO MUCH emotion.",
  "tanto": "TANTALIZE: SO MUCH and yet always out of reach.",
  "tardi": "TARDY student: LATE to every class.",
  "te": "TEA served personally FOR / TO YOU.",
  "temp": "(tempo) TEMPO of TIME: beating its rhythm.",
  "tempo": "TEMPO: the rhythm and beat of TIME.",
  "tenere": "TENACIOUS grip: TO HOLD / KEEP firmly.",
  "tenni": "(tenere) TENNIS match: I HELD the racket tight.",
  "terminava": "(terminare) TERMINATE: WAS ENDING / FINISHING the run.",
  "terra": "TERRAIN: the EARTH / LAND stretching below.",
  "test": "(testa) TEST HEAD: the HEAD of the exam.",
  "ti": "TI musical note: FOR YOU, this note.",
  "tolsi": "(togliere) TOOLS removed: I TOOK AWAY everything.",
  "tra": "TRAP set BETWEEN / AMONG the trees.",
  "trarrotti": "(trarre) TRACTOR pulling you OUT / AWAY from danger.",
  "trattar": "(trattare) TREAT well: TO DEAL WITH / TREAT carefully.",
  "tremar": "(tremare) TREMOR: the ground TREMBLES / SHAKES.",
  "tremesse": "(tremare) TREMBLING endlessly — WAS SHAKING with fear.",
  "troia": "TROJAN Horse: TROY and its legendary wooden trick.",
  "trovai": "(trovare) TROPHY — I FOUND the prize!",
  "tu": "TOO — YOU too are invited.",
  "tua": "(tuo) TUTU skirt: YOUR little costume.",
  "tuo": "TUTOR: YOUR personal teacher and guide.",
  "turno": "TURN: waiting patiently for your TURN.",
  "tutta": "(tutto) TOTAL: ALL of it, the whole thing.",
  "tutte": "(tutto) TOTALLY: ALL things together, feminine.",
  "tutti": "(tutto) TUTTI-FRUITY: EVERYONE eating sweets together.",
  "udirai": "(udire) AUDITORY: YOU WILL HEAR the sound clearly.",
  "umile": "HUMBLE: genuinely HUMBLE and modest.",
  "un": "ONE umbrella: A single thing.",
  "uscito": "(uscire) EXIT sign: GONE OUT through the door.",
  "vagliami": "(valere) VALUE ME: MAY IT AVAIL / HELP ME now.",
  "valle": "VALLEY: a low VALLEY between two peaks.",
  "vederai": "(vedere) VIDEO: YOU WILL SEE it on screen.",
  "vedi": "(vedere) VIDEO: YOU SEE it right now.",
  "vedrai": "(vedere) VIDEO: YOU WILL SEE the footage.",
  "veggia": "(vedere) VEGGIE lover MAY SEE green everywhere.",
  "vegna": "(venire) VEGAN era: MAY COME the plant-based age.",
  "veltro": "VELOCITY ROW — the greyhound: pure speed.",
  "vene": "(venire / vena) VEIN: blood COMES through the VEINS.",
  "venendomi": "(venire) VENOM COMING TO ME — approaching fast.",
  "venire": "VENUE is where people COME TO — TO COME.",
  "venisse": "(venire) VENICE: where everyone COMES to visit.",
  "venne": "(venire) VENUE: CAME to the right meeting point.",
  "verace": "VERA ACE: TRUE / GENUINE ace player.",
  "vergine": "VIRGIN: pure MAIDEN untouched.",
  "vergognosa": "(vergognoso) GONE with SHAME: ASHAMED and hiding.",
  "verra": "(venire) VERANDA: it WILL COME to your doorstep.",
  "vestite": "(vestire) VESTED ceremony: DRESSED / CLOTHED for the occasion.",
  "vi": "VIA there — THERE / FOR YOU.",
  "vide": "(vedere) VIDEO: SAW it captured on film.",
  "vidi": "(vedere) VIDEO: I SAW the footage clearly.",
  "villa": "VILLA: a luxurious country ESTATE / HOUSE.",
  "virgilio": "VIRGIL: the great Roman poet, Dante guide.",
  "virtute": "(virtu) VIRTUE: EXCELLENCE of character and power.",
  "vissi": "(vivere) VISA: I LIVED abroad with a visa.",
  "vista": "VISTA: a stunning VIEW / SIGHT on the horizon.",
  "viva": "VIVA! LONG LIVE the king! Alive and vibrant.",
  "viver": "(vivere) VITAL sign: TO LIVE and breathe.",
  "voglia": "VOGUE: the burning DESIRE to be fashionable.",
  "volge": "(volgere) REVOLVE: TURNS around in circles.",
  "volontieri": "VOLUNTARY act: done WILLINGLY / GLADLY.",
  "volse": "(volgere) VOLTS switched: energy TURNED on.",
  "volsi": "(volgere) VOLTS: I TURNED the electricity on.",
  "volte": "(volta) VAULT of TIMES: TIMES / TURNS in the arch.",
  "volto": "VOLT-O: a FACE charged with electric expression.",
  "volume": "VOLUME knob on a big BOOK — turn it up.",
  "vorrai": "(volere) YOU WILL WANT more of this.",
  "vuo": "(volere) WOO someone: WANTS to charm them.",
  "vuol": "(volere) WOOL coat: WANTS the warm wrap.",
  "viaggio": "(viaggio) VOYAGE: a long JOURNEY across the sea.",
  "volto": "(volto) VOLT: a FACE full of electric energy.",
  "e": "(essere) E = IS. The simplest statement: it IS.",
}

new_entries.update(existing)  # existing entries always win — never overwrite hand-crafted mnemonics
existing = new_entries
with open(path, "w", encoding="utf-8") as f:
    json.dump(existing, f, ensure_ascii=False, indent=2)

print(f"Total entries now: {len(existing)}")
