export interface PhonemeHint {
  display: string;
  phonetic: string;
  audioHint: string;
  category: string;
  tip: string;
}

export const phonemeHints: Record<string, PhonemeHint> = {
  // ── Silent letters ──────────────────────────────────────────────────────────
  "knight":      { display:"NAIT",            phonetic:"naɪt",         audioHint:"nait",               category:"Silent letter",     tip:"'k' and 'gh' are both silent" },
  "knife":       { display:"NAIF",            phonetic:"naɪf",         audioHint:"naif",               category:"Silent letter",     tip:"'k' is silent — same pattern: knock, knee, knit" },
  "lamb":        { display:"LAM",             phonetic:"læm",          audioHint:"lam",                category:"Silent letter",     tip:"Final 'b' is silent — also: bomb, comb, climb" },
  "debt":        { display:"DET",             phonetic:"dɛt",          audioHint:"det",                category:"Silent letter",     tip:"'b' is silent — never say 'deb-t'" },
  "doubt":       { display:"DOWT",            phonetic:"daʊt",         audioHint:"dowt",               category:"Silent letter",     tip:"'b' is silent — say DOWT" },
  "island":      { display:"AI-lund",         phonetic:"aɪlənd",       audioHint:"ai-lund",            category:"Silent letter",     tip:"'s' is completely silent" },
  "wednesday":   { display:"WENZ-day",        phonetic:"wɛnzdeɪ",      audioHint:"wenz-day",           category:"Silent letter",     tip:"First 'd' is silent — WENZ-day not WED-nes-day" },
  "psychology":  { display:"sy-KOL-uh-jee",   phonetic:"saɪˈkɒlədʒi", audioHint:"sy-kol-uh-jee",      category:"Silent letter",     tip:"'p' is completely silent" },
  "pneumonia":   { display:"noo-MOH-nyuh",    phonetic:"njuːˈmoʊniə",  audioHint:"noo-moh-nyuh",       category:"Silent letter",     tip:"'p' is silent — starts with 'n' sound" },
  "autumn":      { display:"AW-tum",          phonetic:"ɔːtəm",        audioHint:"aw-tum",             category:"Silent letter",     tip:"Final 'n' is silent — AW-tum not AW-tumn" },
  "column":      { display:"KOL-um",          phonetic:"kɒləm",        audioHint:"kol-um",             category:"Silent letter",     tip:"Final 'n' is silent" },
  "salmon":      { display:"SAM-un",          phonetic:"sæmən",        audioHint:"sam-un",             category:"Silent letter",     tip:"'l' is completely silent" },
  "half":        { display:"HAF",             phonetic:"hæf",          audioHint:"haf",                category:"Silent letter",     tip:"'l' is silent — say HAF not HALF" },
  "calm":        { display:"KAHM",            phonetic:"kɑːm",         audioHint:"kahm",               category:"Silent letter",     tip:"'l' is silent — KAHM not KALM" },
  "sword":       { display:"SORD",            phonetic:"sɔːrd",        audioHint:"sord",               category:"Silent letter",     tip:"'w' is silent — SORD not SWORE-d" },
  "castle":      { display:"KAS-ul",          phonetic:"ˈkæsəl",       audioHint:"kas-ul",             category:"Silent letter",     tip:"'t' is silent — KAS-ul not KAS-tul" },
  "listen":      { display:"LIS-un",          phonetic:"ˈlɪsən",       audioHint:"lis-un",             category:"Silent letter",     tip:"'t' is silent — LIS-un not LIS-ten" },
  "fasten":      { display:"FAS-un",          phonetic:"ˈfæsən",       audioHint:"fas-un",             category:"Silent letter",     tip:"'t' is silent" },
  "receipt":     { display:"rih-SEET",        phonetic:"rɪˈsiːt",      audioHint:"rih-seet",           category:"Silent letter",     tip:"'p' is silent — never say 'recei-pt'" },
  "muscle":      { display:"MUS-ul",          phonetic:"ˈmʌsəl",       audioHint:"mus-ul",             category:"Silent letter",     tip:"'c' is silent — MUS-ul not MUSK-ul" },
  "heir":        { display:"AIR",             phonetic:"ɛr",           audioHint:"air",                category:"Silent letter",     tip:"'h' is silent — sounds exactly like 'air'" },
  "honest":      { display:"ON-ist",          phonetic:"ˈɒnɪst",       audioHint:"on-ist",             category:"Silent letter",     tip:"'h' is silent — ON-ist not HON-est" },
  "hour":        { display:"OW-er",           phonetic:"ˈaʊər",        audioHint:"ow-er",              category:"Silent letter",     tip:"'h' is silent — sounds like 'our'" },
  "wrist":       { display:"RIST",            phonetic:"rɪst",         audioHint:"rist",               category:"Silent letter",     tip:"'w' is silent — all 'wr-' words: write, wrong, wrap" },
  "gnaw":        { display:"NAW",             phonetic:"nɔː",          audioHint:"naw",                category:"Silent letter",     tip:"'g' is silent before 'n'" },
  "sign":        { display:"SINE",            phonetic:"saɪn",         audioHint:"sine",               category:"Silent letter",     tip:"'g' is silent — rhymes with 'mine'" },
  "reign":       { display:"RAYN",            phonetic:"reɪn",         audioHint:"rayn",               category:"Silent letter",     tip:"'g' and 'ei' create long 'a' — rhymes with 'rain'" },
  "rhyme":       { display:"RAIM",            phonetic:"raɪm",         audioHint:"raim",               category:"Silent letter",     tip:"'h' is silent — RAIM" },
  "subtle":      { display:"SUT-ul",          phonetic:"ˈsʌtəl",       audioHint:"sut-ul",             category:"Silent letter",     tip:"'b' is silent, 'tle' = 'ul'" },
  "honour":      { display:"ON-er",           phonetic:"ˈɒnər",        audioHint:"on-er",              category:"Silent letter",     tip:"'h' is silent — British spelling of 'honor'" },
  "ghost":       { display:"GOHST",           phonetic:"ɡoʊst",        audioHint:"gohst",              category:"Silent letter",     tip:"'h' is silent — GOHST" },
  "fascinate":   { display:"FAS-ih-nayt",     phonetic:"ˈfæsɪneɪt",   audioHint:"fas-ih-nayt",        category:"Silent letter",     tip:"'c' is silent — FAS-ih-nayt" },
  "portrait":    { display:"POR-trit",        phonetic:"ˈpɔːrtrɪt",   audioHint:"por-trit",           category:"Silent letter",     tip:"Middle 't' is often dropped — POR-trit not POR-tray-it" },
  "handsome":    { display:"HAN-sum",         phonetic:"ˈhænsəm",      audioHint:"han-sum",            category:"Silent letter",     tip:"'d' is silent — HAN-sum not HAND-sum" },
  "answer":      { display:"AN-ser",          phonetic:"ˈænsər",       audioHint:"an-ser",             category:"Silent letter",     tip:"'w' is silent — AN-ser" },

  // ── Vowel traps ─────────────────────────────────────────────────────────────
  "women":       { display:"WIM-in",          phonetic:"ˈwɪmɪn",       audioHint:"wim-in",             category:"Vowel trap",        tip:"'o' sounds like short 'i' — never WOE-men" },
  "colonel":     { display:"KUR-nul",         phonetic:"ˈkɜːrnəl",     audioHint:"kur-nul",            category:"Vowel trap",        tip:"Sounds like 'kernel' — totally different from spelling" },
  "blood":       { display:"BLUD",            phonetic:"blʌd",         audioHint:"blud",               category:"Vowel trap",        tip:"'oo' sounds like short 'u' — rhymes with 'mud'" },
  "flood":       { display:"FLUD",            phonetic:"flʌd",         audioHint:"flud",               category:"Vowel trap",        tip:"'oo' sounds like short 'u' — rhymes with 'mud'" },
  "enough":      { display:"ih-NUF",          phonetic:"ɪˈnʌf",        audioHint:"ih-nuf",             category:"Vowel trap",        tip:"'ough' = 'uff' — rhymes with 'stuff'" },
  "tough":       { display:"TUF",             phonetic:"tʌf",          audioHint:"tuf",                category:"Vowel trap",        tip:"'ough' = 'uff' — rhymes with 'stuff'" },
  "though":      { display:"THOH",            phonetic:"ðoʊ",          audioHint:"thoh",               category:"Vowel trap",        tip:"'ough' = long 'o' — rhymes with 'go'" },
  "through":     { display:"THROO",           phonetic:"θruː",         audioHint:"throo",              category:"Vowel trap",        tip:"'ough' = 'oo' — rhymes with 'blue'" },
  "thought":     { display:"THAWT",           phonetic:"θɔːt",         audioHint:"thawt",              category:"Vowel trap",        tip:"'ough' = 'aw' — rhymes with 'caught'" },
  "cough":       { display:"KOF",             phonetic:"kɒf",          audioHint:"kof",                category:"Vowel trap",        tip:"'ough' = 'off' — rhymes with 'off'" },
  "bureau":      { display:"BYUR-oh",         phonetic:"ˈbjʊroʊ",      audioHint:"byur-oh",            category:"Vowel trap",        tip:"'eau' = 'oh' — BYUR-oh" },
  "beautiful":   { display:"BYOO-tih-ful",    phonetic:"ˈbjuːtɪfəl",   audioHint:"byoo-tih-ful",       category:"Vowel trap",        tip:"'beau' = 'byoo' — starts with a 'y' glide" },
  "ocean":       { display:"OH-shun",         phonetic:"ˈoʊʃən",       audioHint:"oh-shun",            category:"Vowel trap",        tip:"'ce' = 'sh' — OH-shun not OH-see-an" },
  "fierce":      { display:"FEERSS",          phonetic:"fɪrs",         audioHint:"feerss",             category:"Vowel trap",        tip:"'ie' = long 'ee' — FEERSS" },
  "vague":       { display:"VAYG",            phonetic:"veɪɡ",         audioHint:"vayg",               category:"Vowel trap",        tip:"'ue' is silent — VAYG not VAY-gyoo" },
  "unique":      { display:"yoo-NEEK",        phonetic:"juːˈniːk",     audioHint:"yoo-neek",           category:"Vowel trap",        tip:"Starts with 'y' glide — yoo-NEEK" },
  "opaque":      { display:"oh-PAYK",         phonetic:"oʊˈpeɪk",      audioHint:"oh-payk",            category:"Vowel trap",        tip:"'que' = 'k' — oh-PAYK" },
  "naive":       { display:"nah-EEV",         phonetic:"naɪˈiːv",      audioHint:"nah-eev",            category:"Vowel trap",        tip:"'ai' = 'ah-ee' — two syllables: nah-EEV" },
  "melancholy":  { display:"MEL-un-kol-ee",   phonetic:"ˈmɛlənkɒli",   audioHint:"mel-un-kol-ee",      category:"Vowel trap",        tip:"Stress on first syllable — MEL-un-kol-ee" },
  "aesthetic":   { display:"es-THET-ik",      phonetic:"ɛsˈθɛtɪk",    audioHint:"es-thet-ik",         category:"Vowel trap",        tip:"'ae' = 'e' — es-THET-ik not ay-es-THET-ik" },
  "exquisite":   { display:"EK-skwiz-it",     phonetic:"ˈɛkskwɪzɪt",   audioHint:"ek-skwiz-it",        category:"Vowel trap",        tip:"Stress on first syllable — EK-skwiz-it" },
  "scarlet":     { display:"SKAR-let",        phonetic:"ˈskɑːrlɪt",    audioHint:"skar-let",           category:"Vowel trap",        tip:"'ar' = 'ahr' — SKAR-let" },
  "bizarre":     { display:"bih-ZAR",         phonetic:"bɪˈzɑːr",      audioHint:"bih-zar",            category:"Vowel trap",        tip:"Stress on second syllable — bih-ZAR" },
  "facade":      { display:"fuh-SAHD",        phonetic:"fəˈsɑːd",      audioHint:"fuh-sahd",           category:"Vowel trap",        tip:"'ç' = 's'; final 'e' is silent — fuh-SAHD" },
  "ennui":       { display:"on-WEE",          phonetic:"ɒnˈwiː",       audioHint:"on-wee",             category:"Vowel trap",        tip:"French loanword — on-WEE not EN-yoo-ee" },
  "debut":       { display:"DAY-byoo",        phonetic:"ˈdeɪbjuː",     audioHint:"day-byoo",           category:"Vowel trap",        tip:"French origin — DAY-byoo, final 't' is silent" },
  "memoir":      { display:"MEM-wahr",        phonetic:"ˈmɛmwɑːr",     audioHint:"mem-wahr",           category:"Vowel trap",        tip:"'oir' = 'wahr' — MEM-wahr" },
  "rendezvous":  { display:"RON-day-voo",     phonetic:"ˈrɒndeɪvuː",   audioHint:"ron-day-voo",        category:"Vowel trap",        tip:"French: 'ez' = 'ay', 's' silent — RON-day-voo" },
  "blasé":       { display:"blah-ZAY",        phonetic:"blɑːˈzeɪ",     audioHint:"blah-zay",           category:"Vowel trap",        tip:"French origin — blah-ZAY, accent shows long 'ay'" },
  "hypocrisy":   { display:"hih-POK-rih-see", phonetic:"hɪˈpɒkrɪsi",   audioHint:"hih-pok-rih-see",    category:"Vowel trap",        tip:"'y' = 'ih' — hih-POK-rih-see" },

  // ── T-flapping (AmE) ─────────────────────────────────────────────────────────
  "butter":      { display:"BUD-er",          phonetic:"ˈbʌɾər",       audioHint:"bud-er",             category:"T-flapping (AmE)",  tip:"Between vowels, 't' sounds like 'd' in AmE" },
  "water":       { display:"WAD-er",          phonetic:"ˈwɑːɾər",      audioHint:"wad-er",             category:"T-flapping (AmE)",  tip:"'t' between vowels becomes a flapped 'd'" },
  "better":      { display:"BED-er",          phonetic:"ˈbɛɾər",       audioHint:"bed-er",             category:"T-flapping (AmE)",  tip:"Double 't' between vowels sounds like 'd'" },
  "matter":      { display:"MAD-er",          phonetic:"ˈmæɾər",       audioHint:"mad-er",             category:"T-flapping (AmE)",  tip:"'tt' between vowels = quick 'd'" },
  "pretty":      { display:"PRID-ee",         phonetic:"ˈprɪɾi",       audioHint:"prid-ee",            category:"T-flapping (AmE)",  tip:"'tt' flaps to 'd' in fast AmE speech" },
  "little":      { display:"LID-ul",          phonetic:"ˈlɪɾəl",       audioHint:"lid-ul",             category:"T-flapping (AmE)",  tip:"'tt' becomes a flap — sounds like 'liddle'" },
  "bottle":      { display:"BOD-ul",          phonetic:"ˈbɑːɾəl",      audioHint:"bod-ul",             category:"T-flapping (AmE)",  tip:"'tt' flaps — sounds like 'boddle'" },
  "metal":       { display:"MED-ul",          phonetic:"ˈmɛɾəl",       audioHint:"med-ul",             category:"T-flapping (AmE)",  tip:"'t' flaps — metal sounds like medal in AmE" },
  "city":        { display:"SID-ee",          phonetic:"ˈsɪɾi",        audioHint:"sid-ee",             category:"T-flapping (AmE)",  tip:"'t' between vowels = 'd' sound" },
  "getting":     { display:"GED-ing",         phonetic:"ˈɡɛɾɪŋ",       audioHint:"ged-ing",            category:"T-flapping (AmE)",  tip:"'tt' flaps to 'd' — GED-ing" },
  "letter":      { display:"LED-er",          phonetic:"ˈlɛɾər",       audioHint:"led-er",             category:"T-flapping (AmE)",  tip:"'tt' flaps — letter sounds almost like 'ledder'" },
  "satin":       { display:"SAD-in",          phonetic:"ˈsæɾɪn",       audioHint:"sad-in",             category:"T-flapping (AmE)",  tip:"'t' between vowels flaps — SAD-in in AmE" },
  "society":     { display:"suh-SY-uh-tee",   phonetic:"səˈsaɪəti",    audioHint:"suh-sy-uh-tee",      category:"T-flapping (AmE)",  tip:"Middle 't' flaps — suh-SY-uh-dee in natural speech" },

  // ── Glide insertion ─────────────────────────────────────────────────────────
  "language":    { display:"LANG-gwij",       phonetic:"ˈlæŋɡwɪdʒ",   audioHint:"lang-gwidge",        category:"Glide insertion",   tip:"'u+a' creates a 'w' glide — lang-GWIDGE" },
  "jaguar":      { display:"JAG-wahr",        phonetic:"ˈdʒæɡwɑːr",   audioHint:"jag-wahr",           category:"Glide insertion",   tip:"'u+a' creates a 'w' glide between syllables" },
  "perpetual":   { display:"per-PECH-oo-ul",  phonetic:"pərˈpɛtʃuəl", audioHint:"per-pech-oo-ul",     category:"Glide insertion",   tip:"'tu' sounds like 'choo' in AmE" },
  "mutual":      { display:"MYOO-choo-ul",    phonetic:"ˈmjuːtʃuəl",  audioHint:"myoo-choo-ul",       category:"Glide insertion",   tip:"'tu' = 'choo' — myoo-CHOO-ul" },
  "actual":      { display:"AK-choo-ul",      phonetic:"ˈæktʃuəl",    audioHint:"ak-choo-ul",         category:"Glide insertion",   tip:"'tu' = 'choo' — very common in spoken English" },
  "graduate":    { display:"GRAJ-oo-ayt",     phonetic:"ˈɡrædʒueɪt",  audioHint:"graj-oo-ate",        category:"Glide insertion",   tip:"'du' = 'joo' — GRAJ-oo-ate" },
  "picture":     { display:"PIK-cher",        phonetic:"ˈpɪktʃər",    audioHint:"pik-cher",           category:"Glide insertion",   tip:"'tu' = 'ch' — PIK-cher not PIK-tyoor" },
  "nature":      { display:"NAY-cher",        phonetic:"ˈneɪtʃər",    audioHint:"nay-cher",           category:"Glide insertion",   tip:"'tu' = 'ch' — NAY-cher not NAY-tyoor" },
  "feature":     { display:"FEE-cher",        phonetic:"ˈfiːtʃər",    audioHint:"fee-cher",           category:"Glide insertion",   tip:"'tu' = 'ch' — FEE-cher" },
  "future":      { display:"FYOO-cher",       phonetic:"ˈfjuːtʃər",   audioHint:"fyoo-cher",          category:"Glide insertion",   tip:"'tu' = 'ch' — FYOO-cher not FYOO-tyoor" },
  "creature":    { display:"KREE-cher",       phonetic:"ˈkriːtʃər",   audioHint:"kree-cher",          category:"Glide insertion",   tip:"'tu' = 'ch' — KREE-cher" },
  "culture":     { display:"KUL-cher",        phonetic:"ˈkʌltʃər",    audioHint:"kul-cher",           category:"Glide insertion",   tip:"'tu' = 'ch' — KUL-cher" },
  "luxury":      { display:"LUK-zhuh-ree",    phonetic:"ˈlʌkʃəri",    audioHint:"luk-zhuh-ree",       category:"Glide insertion",   tip:"'xu' = 'zh' — LUK-zhuh-ree not LUG-zhoo-ree" },
  "luxurious":   { display:"lug-ZHOOR-ee-us", phonetic:"lʌɡˈʒʊəriəs", audioHint:"lug-zhoor-ee-us",    category:"Glide insertion",   tip:"'xu' = 'zh' — lug-ZHOOR-ee-us" },
  "peculiar":    { display:"pih-KYOOL-yer",   phonetic:"pɪˈkjuːliər", audioHint:"pih-kyool-yer",      category:"Glide insertion",   tip:"'u' creates 'y' glide — pih-KYOOL-yer" },

  // ── Consonant shifts ─────────────────────────────────────────────────────────
  "character":   { display:"KAR-ik-ter",      phonetic:"ˈkærɪktər",   audioHint:"kar-ik-ter",         category:"Consonant shift",   tip:"'ch' = 'k' — from Greek origin" },
  "chemistry":   { display:"KEM-is-tree",     phonetic:"ˈkɛmɪstri",   audioHint:"kem-is-tree",        category:"Consonant shift",   tip:"'ch' = 'k' — KEM not CHEM" },
  "chaos":       { display:"KAY-os",          phonetic:"ˈkeɪɒs",      audioHint:"kay-os",             category:"Consonant shift",   tip:"'ch' = 'k' — KAY-os not CHAY-os" },
  "choir":       { display:"KWIRE",           phonetic:"ˈkwaɪər",     audioHint:"kwire",              category:"Consonant shift",   tip:"'ch' = 'kw' — KWIRE not CHORE" },
  "schedule":    { display:"SKED-jool",       phonetic:"ˈskɛdʒuːl",   audioHint:"sked-jool",          category:"Consonant shift",   tip:"AmE: 'sch' = 'sk' (British say SHED-yool)" },
  "conscience":  { display:"KON-shuns",       phonetic:"ˈkɒnʃəns",    audioHint:"kon-shuns",          category:"Consonant shift",   tip:"'sci' = 'sh' — KON-shuns not KON-see-ents" },
  "special":     { display:"SPESH-ul",        phonetic:"ˈspɛʃəl",     audioHint:"spesh-ul",           category:"Consonant shift",   tip:"'ci' = 'sh' — SPESH-ul" },
  "social":      { display:"SOH-shul",        phonetic:"ˈsoʊʃəl",     audioHint:"soh-shul",           category:"Consonant shift",   tip:"'ci' = 'sh' — SOH-shul" },
  "vision":      { display:"VIZH-un",         phonetic:"ˈvɪʒən",      audioHint:"vizh-un",            category:"Consonant shift",   tip:"'si' = 'zh' — like the 's' in 'measure'" },
  "decision":    { display:"dih-SIZH-un",     phonetic:"dɪˈsɪʒən",    audioHint:"dih-sizh-un",        category:"Consonant shift",   tip:"'si' = 'zh' — dih-SIZH-un" },
  "measure":     { display:"MEZH-er",         phonetic:"ˈmɛʒər",      audioHint:"mezh-er",            category:"Consonant shift",   tip:"'su' = 'zh' — MEZH-er not MEE-sure" },
  "treasure":    { display:"TREZH-er",        phonetic:"ˈtrɛʒər",     audioHint:"trezh-er",           category:"Consonant shift",   tip:"'su' = 'zh' — TREZH-er" },
  "pleasure":    { display:"PLEZH-er",        phonetic:"ˈplɛʒər",     audioHint:"plezh-er",           category:"Consonant shift",   tip:"'su' = 'zh' — PLEZH-er" },
  "usual":       { display:"YOO-zhul",        phonetic:"ˈjuːʒuəl",    audioHint:"yoo-zhul",           category:"Consonant shift",   tip:"'su' = 'zh' — YOO-zhul not YOO-zoo-ul" },
  "anxiety":     { display:"ang-ZY-uh-tee",   phonetic:"æŋˈzaɪəti",   audioHint:"ang-zy-uh-tee",      category:"Consonant shift",   tip:"'x' before stressed vowel = 'gz' — ang-ZY-uh-tee" },
  "exact":       { display:"eg-ZAKT",         phonetic:"ɪɡˈzækt",     audioHint:"eg-zakt",            category:"Consonant shift",   tip:"'x' before stressed vowel = 'gz'" },
  "genre":       { display:"ZHON-ruh",        phonetic:"ˈʒɑːnrə",     audioHint:"zhon-ruh",           category:"Consonant shift",   tip:"French: 'g' = 'zh' soft sound — ZHON-ruh" },
  "malicious":   { display:"muh-LISH-us",     phonetic:"məˈlɪʃəs",    audioHint:"muh-lish-us",        category:"Consonant shift",   tip:"'ci' = 'sh' — muh-LISH-us" },
  "vicious":     { display:"VISH-us",         phonetic:"ˈvɪʃəs",      audioHint:"vish-us",            category:"Consonant shift",   tip:"'ci' = 'sh' — VISH-us not VIK-ee-us" },
  "precious":    { display:"PRESH-us",        phonetic:"ˈprɛʃəs",     audioHint:"presh-us",           category:"Consonant shift",   tip:"'ci' = 'sh' — PRESH-us" },
  "unconscious": { display:"un-KON-shus",     phonetic:"ʌnˈkɒnʃəs",   audioHint:"un-kon-shus",        category:"Consonant shift",   tip:"'sci' = 'sh' — un-KON-shus" },
  "sufficient":  { display:"suh-FISH-unt",    phonetic:"səˈfɪʃənt",   audioHint:"suh-fish-unt",       category:"Consonant shift",   tip:"'ci' = 'sh' — suh-FISH-unt" },
  "magnificent": { display:"mag-NIF-ih-sent",  phonetic:"mæɡˈnɪfɪsənt",audioHint:"mag-nif-ih-sent",   category:"Consonant shift",   tip:"Stress on second syllable — mag-NIF-ih-sent" },

  // ── Stress reduction ─────────────────────────────────────────────────────────
  "comfortable": { display:"KUMF-ter-bul",    phonetic:"ˈkʌmftərbəl", audioHint:"kumf-ter-bul",       category:"Stress reduction",  tip:"3 syllables in AmE — KUMF-ter-bul not KUMF-for-tuh-bul" },
  "interesting": { display:"IN-trest-ing",    phonetic:"ˈɪntrɛstɪŋ",  audioHint:"in-trest-ing",       category:"Stress reduction",  tip:"3 syllables — IN-trest-ing not IN-ter-est-ing" },
  "chocolate":   { display:"CHOK-lit",        phonetic:"ˈtʃɒklɪt",    audioHint:"chok-lit",           category:"Stress reduction",  tip:"2 syllables — CHOK-lit not CHOK-oh-late" },
  "probably":    { display:"PROB-lee",        phonetic:"ˈprɒbli",      audioHint:"prob-lee",           category:"Stress reduction",  tip:"Often 2 syllables in fast speech — PROB-lee" },
  "every":       { display:"EV-ree",          phonetic:"ˈɛvri",        audioHint:"ev-ree",             category:"Stress reduction",  tip:"Usually 2 syllables — EV-ree not EV-er-ee" },
  "family":      { display:"FAM-lee",         phonetic:"ˈfæmli",       audioHint:"fam-lee",            category:"Stress reduction",  tip:"Often 2 syllables in fast speech" },
  "different":   { display:"DIF-rent",        phonetic:"ˈdɪfrənt",     audioHint:"dif-rent",           category:"Stress reduction",  tip:"Often 2 syllables in fast speech" },
  "average":     { display:"AV-rij",          phonetic:"ˈævrɪdʒ",      audioHint:"av-rij",             category:"Stress reduction",  tip:"Often 2 syllables — AV-rij not AV-er-ij" },
  "extraordinary":{ display:"ek-STROR-dih-nair-ee", phonetic:"ɪkˈstrɔːrdɪnɛri", audioHint:"ek-stror-dih-nair-ee", category:"Stress reduction", tip:"Stress on 2nd syllable — ek-STROR-dih-nair-ee, 6 syllables" },
  "immediately": { display:"ih-MEE-dee-it-lee",phonetic:"ɪˈmiːdiətli", audioHint:"ih-mee-dee-it-lee",  category:"Stress reduction",  tip:"Often 4 syllables — ih-MEE-dee-it-lee" },
  "particularly":{ display:"per-TIK-yuh-lee", phonetic:"pərˈtɪkjələrli",audioHint:"per-tik-yuh-lee",  category:"Stress reduction",  tip:"Often reduced — per-TIK-yuh-lee" },
  "aristocracy": { display:"air-is-TOK-ruh-see",phonetic:"ˌærɪˈstɒkrəsi",audioHint:"air-is-tok-ruh-see", category:"Stress reduction", tip:"Stress on 3rd syllable — air-is-TOK-ruh-see" },
  "photography": { display:"fuh-TOG-ruh-fee", phonetic:"fəˈtɒɡrəfi",  audioHint:"fuh-tog-ruh-fee",    category:"Stress reduction",  tip:"Stress on 2nd syllable — fuh-TOG-ruh-fee" },
  "philosophy":  { display:"fih-LOS-uh-fee",  phonetic:"fɪˈlɒsəfi",   audioHint:"fih-los-uh-fee",     category:"Stress reduction",  tip:"Stress on 2nd syllable — fih-LOS-uh-fee" },

  // ── R-colored vowels (AmE) ───────────────────────────────────────────────────
  "world":       { display:"WURLD",           phonetic:"wɜːrld",       audioHint:"wurld",              category:"R-colored vowel",   tip:"'or' = 'ur' — WURLD not WORELD" },
  "bird":        { display:"BURD",            phonetic:"bɜːrd",        audioHint:"burd",               category:"R-colored vowel",   tip:"'ir' = 'ur' — BURD not BIRD with short i" },
  "heard":       { display:"HURD",            phonetic:"hɜːrd",        audioHint:"hurd",               category:"R-colored vowel",   tip:"'ear' = 'ur' — HURD rhymes with 'word'" },
  "learn":       { display:"LURN",            phonetic:"lɜːrn",        audioHint:"lurn",               category:"R-colored vowel",   tip:"'ear' = 'ur' — LURN not LEE-urn" },
  "early":       { display:"UR-lee",          phonetic:"ˈɜːrli",       audioHint:"ur-lee",             category:"R-colored vowel",   tip:"'ear' = 'ur' — UR-lee" },
  "earth":       { display:"URTH",            phonetic:"ɜːrθ",         audioHint:"urth",               category:"R-colored vowel",   tip:"'ear' = 'ur' — URTH not EE-arth" },
  "worth":       { display:"WURTH",           phonetic:"wɜːrθ",        audioHint:"wurth",              category:"R-colored vowel",   tip:"'or' = 'ur' — WURTH" },
  "work":        { display:"WURK",            phonetic:"wɜːrk",        audioHint:"wurk",               category:"R-colored vowel",   tip:"'or' = 'ur' — WURK not WORK with short o" },
  "curious":     { display:"KYOOR-ee-us",     phonetic:"ˈkjʊəriəs",   audioHint:"kyoor-ee-us",        category:"R-colored vowel",   tip:"'ur' = 'oor' — KYOOR-ee-us" },
  "serious":     { display:"SEER-ee-us",      phonetic:"ˈsɪəriəs",    audioHint:"seer-ee-us",         category:"R-colored vowel",   tip:"'er' before 'i' = 'eer' — SEER-ee-us" },
  "superior":    { display:"suh-PEER-ee-er",  phonetic:"suːˈpɪəriər",  audioHint:"suh-peer-ee-er",     category:"R-colored vowel",   tip:"Stress on 2nd syllable — suh-PEER-ee-er" },
};
